### ISSUE TITLE
Crash while loading Decsync state

### ISSUE THREAD

**Issue by jameysharp** [39aldo39/spaRSS-DecSync#9]
I installed version 1.13.10 from F-Droid. My phone is an old Nexus 6 running Android 7.1.1, if that matters.

I successfully ran the app once, added some feeds, and closed it. Then I set up SyncThing to sync the Decsync directory with FeedReader on my Linux laptop. Since then, every attempt to start this app has crashed, and I also periodically get messages popping up that the background service has crashed.

In both cases the Decsync library is at the top of the stack trace, but I don't understand what's going on well enough to tell whether the bug belongs there or here, so I thought I'd try here first.

Here's the `logcat` output I got from attempting to launch the app:

```
11-03 18:18:22.714   862 16870 I ActivityManager: START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 pkg=org.decsync.sparss.floss cmp=org.decsync.sparss.floss/org.decsync.sparss.activity.HomeActivity bnds=[70,1002][238,1170]} from uid 1000 on display 0
11-03 18:18:22.806   862 25192 I ActivityManager: Start proc 19685:org.decsync.sparss.floss/u0a76 for activity org.decsync.sparss.floss/org.decsync.sparss.activity.HomeActivity
11-03 18:18:22.885 19685 19685 I art     : Starting a blocking GC AddRemoveAppImageSpace
11-03 18:18:22.887 19685 19685 W System  : ClassLoader referenced unknown path: /data/app/org.decsync.sparss.floss-1/lib/arm
11-03 18:18:23.013 19685 19685 I AppCompatViewInflater: app:theme is now deprecated. Please move to using android:theme instead.
11-03 18:18:23.071 19685 19685 I ViewConfigCompat: Could not find method getScaledScrollFactor() on ViewConfiguration
11-03 18:18:23.088 19685 19685 I FloatingActionButton: Setting a custom background is not supported.
11-03 18:18:23.129 19685 19685 I FloatingActionButton: Setting a custom background is not supported.
11-03 18:18:23.169 19685 19685 D DecSync : Execute all new entries in /storage/emulated/0/DecSync/rss
11-03 18:18:25.019 19685 19685 D DecSync : Execute entries of [articles, read, 2019, 10, 03]
11-03 18:18:25.021 19685 19685 D AndroidRuntime: Shutting down VM
11-03 18:18:25.031 19685 19685 E AndroidRuntime: FATAL EXCEPTION: main
11-03 18:18:25.031 19685 19685 E AndroidRuntime: Process: org.decsync.sparss.floss, PID: 19685
11-03 18:18:25.031 19685 19685 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{org.decsync.sparss.floss/org.decsync.sparss.activity.HomeActivity}: java.lang.ArrayIndexOutOfBoundsException: length=116; regionStart=533; regionLength=116
11-03 18:18:25.031 19685 19685 E AndroidRuntime:        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2665)
11-03 18:18:25.031 19685 19685 E AndroidRuntime:        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2726)
11-03 18:18:25.031 19685 19685 E AndroidRuntime:        at android.app.ActivityThread.-wrap12(ActivityThread.java)
11-03 18:18:25.031 19685 19685 E AndroidRuntime:        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1477)
11-03 18:18:25.031 19685 19685 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:102)
11-03 18:18:25.031 19685 19685 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:154)
11-03 18:18:25.031 19685 19685 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:6119)
11-03 18:18:25.031 19685 19685 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
11-03 18:18:25.031 19685 19685 E AndroidRuntime:        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
11-03 18:18:25.031 19685 19685 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
11-03 18:18:25.031 19685 19685 E AndroidRuntime: Caused by: java.lang.ArrayIndexOutOfBoundsException: length=116; regionStart=533; regionLength=116
11-03 18:18:25.031 19685 19685 E AndroidRuntime:        at java.util.Arrays.checkOffsetAndCount(Arrays.java:4857)
11-03 18:18:25.031 19685 19685 E AndroidRuntime:        at libcore.io.IoBridge.read(IoBridge.java:466)
11-03 18:18:25.031 19685 19685 E AndroidRuntime:        at java.io.FileInputStream.read(FileInputStream.java:252)
11-03 18:18:25.031 19685 19685 E AndroidRuntime:        at org.decsync.library.NativeFile.a(SourceFile:6)
11-03 18:18:25.031 19685 19685 E AndroidRuntime:        at org.decsync.library.DecsyncFile.a(SourceFile:11)
11-03 18:18:25.031 19685 19685 E AndroidRuntime:        at org.decsync.library.Decsync.a(SourceFile:41)
11-03 18:18:25.031 19685 19685 E AndroidRuntime:        at org.decsync.library.Decsync.a(SourceFile:35)
11-03 18:18:25.031 19685 19685 E AndroidRuntime:        at org.decsync.library.Decsync.a(SourceFile:34)
11-03 18:18:25.031 19685 19685 E AndroidRuntime:        at org.decsync.sparss.activity.HomeActivity.onCreate(SourceFile:39)
11-03 18:18:25.031 19685 19685 E AndroidRuntime:        at android.app.Activity.performCreate(Activity.java:6679)
11-03 18:18:25.031 19685 19685 E AndroidRuntime:        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118)
11-03 18:18:25.031 19685 19685 E AndroidRuntime:        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2618)
11-03 18:18:25.031 19685 19685 E AndroidRuntime:        ... 9 more
```

And here's `logcat` output from the `FetcherService` crashing:

```
11-03 18:35:46.123 20133 20149 D DecSync : Execute entries of [articles, read, 2019, 10, 21]
11-03 18:35:46.124 20133 20149 E AndroidRuntime: FATAL EXCEPTION: IntentService[FetcherService]
11-03 18:35:46.124 20133 20149 E AndroidRuntime: Process: org.decsync.sparss.floss, PID: 20133
11-03 18:35:46.124 20133 20149 E AndroidRuntime: java.lang.ArrayIndexOutOfBoundsException: length=507; regionStart=468; regionLength=507
11-03 18:35:46.124 20133 20149 E AndroidRuntime: 	at java.util.Arrays.checkOffsetAndCount(Arrays.java:4857)
11-03 18:35:46.124 20133 20149 E AndroidRuntime: 	at libcore.io.IoBridge.read(IoBridge.java:466)
11-03 18:35:46.124 20133 20149 E AndroidRuntime: 	at java.io.FileInputStream.read(FileInputStream.java:252)
11-03 18:35:46.124 20133 20149 E AndroidRuntime: 	at org.decsync.library.NativeFile.a(SourceFile:6)
11-03 18:35:46.124 20133 20149 E AndroidRuntime: 	at org.decsync.library.DecsyncFile.a(SourceFile:11)
11-03 18:35:46.124 20133 20149 E AndroidRuntime: 	at org.decsync.library.Decsync.a(SourceFile:41)
11-03 18:35:46.124 20133 20149 E AndroidRuntime: 	at org.decsync.library.Decsync.a(SourceFile:35)
11-03 18:35:46.124 20133 20149 E AndroidRuntime: 	at org.decsync.library.Decsync.a(SourceFile:34)
11-03 18:35:46.124 20133 20149 E AndroidRuntime: 	at org.decsync.sparss.service.FetcherService.onHandleIntent(SourceFile:57)
11-03 18:35:46.124 20133 20149 E AndroidRuntime: 	at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:68)
11-03 18:35:46.124 20133 20149 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)
11-03 18:35:46.124 20133 20149 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:154)
11-03 18:35:46.124 20133 20149 E AndroidRuntime: 	at android.os.HandlerThread.run(HandlerThread.java:61)
```

**Comment by 39aldo39** [comment]
I also noticed the crash, the latest version on f-droid should fix it.

**Comment by jameysharp** [comment]
You're right, upgrading to 1.13.11 fixed that crash for me. Thank you!
